### ISSUE TITLE
Unique key in MongoDb

### ISSUE THREAD

**Issue by shivani214** [shivani214/GCCHRConnect#23]
There may be fields in a Mongo collection which may need to hold unique values. For that purpose the key may be made unique by adding a constraint. However, if that constraint is removed accidentally, if the database is recreated or if database is created in a different location, the constraint is absent and it needs to be created again.
For this reason, the constraint needs to be created from application level. Some mechanism must be developed for the same.

**Comment by panshul007** [comment]
You are right, it is a good idea to maintain the uniqueness of a field from the application level. 
But having a backup check in the DB is always a good idea as it can crash ur application. 
So we usually maintain a script for setting up the data base which has the following statements
* Create database and collections 
* Create constraints on the fields
* Create indexes on the fields

We also use a version management for the database that maintains all the changes to the DB. So u can revert back the last changes and transactions which crashed the application. 
Both of the above help recreate the database in all cases.

**Comment by shivani214** [comment]
Thank you for the tips. Will now create a new branch to figure out the same.
